# Generated by Django 3.2.7 on 2026-01-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('features', models.TextField()),
                ('predicted_aqi', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
