# Generated by Django 3.2.7 on 2026-01-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0002_aqiprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
